# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
chartVersion: 0.21.1
image:
  # registry: "ghcr.io"
  repository: ghcr.io/bartaadalbert/kbot
  tag: "v1.1.12-71d31f2-linux-amd64"
  os: linux
  arch: amd64
secret:
  envName: TG_BOT_TOKEN
  tokenName: kbot
  tokenKey: telegramToken
  tokenKeyValue: 12345678:AAEAKIIIIIIIIIIIIIIIIIIIIIIIIIIIIIITOKEN
autoscaling:
  enabled: false
serviceAccount:
  create: false
ingress:
  enabled: true
securityContext:
  privileged: true
